spring:
  application:
    name: dtx-txmsg-demo-bank2
  profiles:
    active: local
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  resources:
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true

server:
  servlet:
    context-path: /bank2
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  use-forward-headers: true


