server:
  port: 56081
swagger:
  enable: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank1?useUnicode=true
    username: root
    password: 123456

rocketmq:
  producer:
    group: producer_bank1
  name-server: 127.0.0.1:9876

logging:
  level:
    root: info
    org:
      springframework:
        web: info
    cn:
      itcast:
        wanxintx:
          ensuredemo: debug


